//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.SalesSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quote", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    [System.SerializableAttribute()]
    public partial class Quote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClient.SalesSvc.Item[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LabourPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PartsETAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PurchaseOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClient.SalesSvc.StatusCode StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalServiceTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClient.SalesSvc.Item[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LabourPrice {
            get {
                return this.LabourPriceField;
            }
            set {
                if ((this.LabourPriceField.Equals(value) != true)) {
                    this.LabourPriceField = value;
                    this.RaisePropertyChanged("LabourPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PartsETA {
            get {
                return this.PartsETAField;
            }
            set {
                if ((this.PartsETAField.Equals(value) != true)) {
                    this.PartsETAField = value;
                    this.RaisePropertyChanged("PartsETA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseOrderID {
            get {
                return this.PurchaseOrderIDField;
            }
            set {
                if ((this.PurchaseOrderIDField.Equals(value) != true)) {
                    this.PurchaseOrderIDField = value;
                    this.RaisePropertyChanged("PurchaseOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceDescription {
            get {
                return this.ServiceDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceDescriptionField, value) != true)) {
                    this.ServiceDescriptionField = value;
                    this.RaisePropertyChanged("ServiceDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClient.SalesSvc.StatusCode Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalServiceTime {
            get {
                return this.TotalServiceTimeField;
            }
            set {
                if ((this.TotalServiceTimeField.Equals(value) != true)) {
                    this.TotalServiceTimeField = value;
                    this.RaisePropertyChanged("TotalServiceTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceTime {
            get {
                return this.ServiceTimeField;
            }
            set {
                if ((this.ServiceTimeField.Equals(value) != true)) {
                    this.ServiceTimeField = value;
                    this.RaisePropertyChanged("ServiceTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusCode", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    public enum StatusCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovedCheckStock = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovedBookService = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovedNotInStock = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETAPendingApproval = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApprovedETA = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Booked = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesSvc.ISalesService")]
    public interface ISalesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetCustomers", ReplyAction="http://tempuri.org/ISalesService/GetCustomersResponse")]
        WebClient.SalesSvc.Customer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetCustomers", ReplyAction="http://tempuri.org/ISalesService/GetCustomersResponse")]
        System.Threading.Tasks.Task<WebClient.SalesSvc.Customer[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetCustomer", ReplyAction="http://tempuri.org/ISalesService/GetCustomerResponse")]
        WebClient.SalesSvc.Customer GetCustomer(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetCustomer", ReplyAction="http://tempuri.org/ISalesService/GetCustomerResponse")]
        System.Threading.Tasks.Task<WebClient.SalesSvc.Customer> GetCustomerAsync(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetQuotes", ReplyAction="http://tempuri.org/ISalesService/GetQuotesResponse")]
        WebClient.SalesSvc.Quote[] GetQuotes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetQuotes", ReplyAction="http://tempuri.org/ISalesService/GetQuotesResponse")]
        System.Threading.Tasks.Task<WebClient.SalesSvc.Quote[]> GetQuotesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetQuote", ReplyAction="http://tempuri.org/ISalesService/GetQuoteResponse")]
        WebClient.SalesSvc.Quote GetQuote(int quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetQuote", ReplyAction="http://tempuri.org/ISalesService/GetQuoteResponse")]
        System.Threading.Tasks.Task<WebClient.SalesSvc.Quote> GetQuoteAsync(int quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/AddNewQuote", ReplyAction="http://tempuri.org/ISalesService/AddNewQuoteResponse")]
        int AddNewQuote(WebClient.SalesSvc.Quote quote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/AddNewQuote", ReplyAction="http://tempuri.org/ISalesService/AddNewQuoteResponse")]
        System.Threading.Tasks.Task<int> AddNewQuoteAsync(WebClient.SalesSvc.Quote quote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ModifyQuote", ReplyAction="http://tempuri.org/ISalesService/ModifyQuoteResponse")]
        void ModifyQuote(WebClient.SalesSvc.Quote quote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ModifyQuote", ReplyAction="http://tempuri.org/ISalesService/ModifyQuoteResponse")]
        System.Threading.Tasks.Task ModifyQuoteAsync(WebClient.SalesSvc.Quote quote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetItems", ReplyAction="http://tempuri.org/ISalesService/GetItemsResponse")]
        WebClient.SalesSvc.Item[] GetItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetItems", ReplyAction="http://tempuri.org/ISalesService/GetItemsResponse")]
        System.Threading.Tasks.Task<WebClient.SalesSvc.Item[]> GetItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ApproveQuote", ReplyAction="http://tempuri.org/ISalesService/ApproveQuoteResponse")]
        void ApproveQuote(int quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/ApproveQuote", ReplyAction="http://tempuri.org/ISalesService/ApproveQuoteResponse")]
        System.Threading.Tasks.Task ApproveQuoteAsync(int quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/RejectQuote", ReplyAction="http://tempuri.org/ISalesService/RejectQuoteResponse")]
        void RejectQuote(int quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/RejectQuote", ReplyAction="http://tempuri.org/ISalesService/RejectQuoteResponse")]
        System.Threading.Tasks.Task RejectQuoteAsync(int quoteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetPartETA", ReplyAction="http://tempuri.org/ISalesService/GetPartETAResponse")]
        System.DateTime GetPartETA(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/GetPartETA", ReplyAction="http://tempuri.org/ISalesService/GetPartETAResponse")]
        System.Threading.Tasks.Task<System.DateTime> GetPartETAAsync(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CheckItemsStockLevel", ReplyAction="http://tempuri.org/ISalesService/CheckItemsStockLevelResponse")]
        WebClient.SalesSvc.Item[] CheckItemsStockLevel(WebClient.SalesSvc.Item[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesService/CheckItemsStockLevel", ReplyAction="http://tempuri.org/ISalesService/CheckItemsStockLevelResponse")]
        System.Threading.Tasks.Task<WebClient.SalesSvc.Item[]> CheckItemsStockLevelAsync(WebClient.SalesSvc.Item[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesServiceChannel : WebClient.SalesSvc.ISalesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesServiceClient : System.ServiceModel.ClientBase<WebClient.SalesSvc.ISalesService>, WebClient.SalesSvc.ISalesService {
        
        public SalesServiceClient() {
        }
        
        public SalesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebClient.SalesSvc.Customer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<WebClient.SalesSvc.Customer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public WebClient.SalesSvc.Customer GetCustomer(int customerID) {
            return base.Channel.GetCustomer(customerID);
        }
        
        public System.Threading.Tasks.Task<WebClient.SalesSvc.Customer> GetCustomerAsync(int customerID) {
            return base.Channel.GetCustomerAsync(customerID);
        }
        
        public WebClient.SalesSvc.Quote[] GetQuotes() {
            return base.Channel.GetQuotes();
        }
        
        public System.Threading.Tasks.Task<WebClient.SalesSvc.Quote[]> GetQuotesAsync() {
            return base.Channel.GetQuotesAsync();
        }
        
        public WebClient.SalesSvc.Quote GetQuote(int quoteID) {
            return base.Channel.GetQuote(quoteID);
        }
        
        public System.Threading.Tasks.Task<WebClient.SalesSvc.Quote> GetQuoteAsync(int quoteID) {
            return base.Channel.GetQuoteAsync(quoteID);
        }
        
        public int AddNewQuote(WebClient.SalesSvc.Quote quote) {
            return base.Channel.AddNewQuote(quote);
        }
        
        public System.Threading.Tasks.Task<int> AddNewQuoteAsync(WebClient.SalesSvc.Quote quote) {
            return base.Channel.AddNewQuoteAsync(quote);
        }
        
        public void ModifyQuote(WebClient.SalesSvc.Quote quote) {
            base.Channel.ModifyQuote(quote);
        }
        
        public System.Threading.Tasks.Task ModifyQuoteAsync(WebClient.SalesSvc.Quote quote) {
            return base.Channel.ModifyQuoteAsync(quote);
        }
        
        public WebClient.SalesSvc.Item[] GetItems() {
            return base.Channel.GetItems();
        }
        
        public System.Threading.Tasks.Task<WebClient.SalesSvc.Item[]> GetItemsAsync() {
            return base.Channel.GetItemsAsync();
        }
        
        public void ApproveQuote(int quoteID) {
            base.Channel.ApproveQuote(quoteID);
        }
        
        public System.Threading.Tasks.Task ApproveQuoteAsync(int quoteID) {
            return base.Channel.ApproveQuoteAsync(quoteID);
        }
        
        public void RejectQuote(int quoteID) {
            base.Channel.RejectQuote(quoteID);
        }
        
        public System.Threading.Tasks.Task RejectQuoteAsync(int quoteID) {
            return base.Channel.RejectQuoteAsync(quoteID);
        }
        
        public System.DateTime GetPartETA(string description) {
            return base.Channel.GetPartETA(description);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetPartETAAsync(string description) {
            return base.Channel.GetPartETAAsync(description);
        }
        
        public WebClient.SalesSvc.Item[] CheckItemsStockLevel(WebClient.SalesSvc.Item[] items) {
            return base.Channel.CheckItemsStockLevel(items);
        }
        
        public System.Threading.Tasks.Task<WebClient.SalesSvc.Item[]> CheckItemsStockLevelAsync(WebClient.SalesSvc.Item[] items) {
            return base.Channel.CheckItemsStockLevelAsync(items);
        }
    }
}
